version: '3'
services:
  app:
    image: treerspeaking/random-num-generator-app:v1
    container_name: app
    build: ./nginx
    depends_on:
      - server
      - front
    ports:
      - 80:80
  front:
    image: treerspeaking/random-num-generator-front-end:v1
    container_name: front-end
    build: ./client
    depends_on:
      - server
    ports:
      - "3000:3000"
    # watch:
    #   - ./src
      # - node_modules
  server:
    image: treerspeaking/random-num-generator-back-end:v1
    container_name: back-end
    build: ./server
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync
          path: ./
          target: /
          # ignore:
          #   - node_modules/
        - action: rebuild
          path: package.json

      # - node_modules