# Use the official Nginx image as the base
FROM curlimages/curl:latest
FROM nginx:latest

# Copy the default Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the default Nginx port (80)
EXPOSE 80

# Run Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
