# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - treerspeaking1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_80ffa4a88ae84e6db654a36ed8372a6d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_47ea8673a9254590a37a509c0ab53555 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_80ffa4a88ae84e6db654a36ed8372a6d }}/myserver:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'treerspeaking1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6d7712c8b0b6488f82e53aee11d2d016 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_80ffa4a88ae84e6db654a36ed8372a6d }}/myserver:${{ github.sha }}'